services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
      target: prod-runner
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
