services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev-runner
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app/src
        - action: rebuild
          path: ./src/package.json
    command: ["npm", "run", "dev"]
    ports:
      - ${PORT}:${PORT}
    depends_on:
      database:
        condition: service_healthy

  database:
    image: postgres:17.0
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - db-store:/var/lib/postgresql/data
    healthcheck:
      test: "psql -U ${DB_USER}"
      interval: 3s
      timeout: 3s
      retries: 0
      start_period: 10s

volumes:
  db-store:
