services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev-runner
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app/src
        - action: rebuild
          path: ./src/package.json
    command: ["pnpm", "dev"]
    environment:
      NODE_ENV: development
      TZ: UTC
    ports:
      - 3000:3000
      - 5555:5555

  database:
    image: postgres:16.3
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
      TZ: UTC
    ports:
      - 5432:5432
    volumes:
      - db-store:/var/lib/postgresql/data

volumes:
  db-store:
