import CssBaseline from '@mui/material/CssBaseline';
import InitColorSchemeScript from '@mui/material/InitColorSchemeScript';
import { ThemeProvider } from '@mui/material/styles';
import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter';
import { Roboto } from 'next/font/google';
import Head from 'next/head';
import { ReactNode } from 'react';

import { PresentationLayout } from '@/app/_components/PresentationLayout';
import { MeProvider } from '@/app/_providers/MeProvider';
import { serverClient } from '@/utils/supabase/serverClient';

import theme from './_lib/theme';

import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const roboto = Roboto({
  weight: ['300', '400', '500', '700'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-roboto',
});

export default async function Layout({
  children,
  auth,
}: Readonly<{
  children: ReactNode;
  auth: ReactNode;
}>) {
  const supabase = await serverClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();

  return (
    <html lang="en" suppressHydrationWarning>
      <Head>
        <meta name="viewport" content="initial-scale=1, width=device-width" />
      </Head>
      <body className={roboto.variable}>
        <InitColorSchemeScript attribute="class" />
        <MeProvider user={user}>
          <AppRouterCacheProvider>
            <ThemeProvider theme={theme} defaultMode="system">
              <CssBaseline />
              <PresentationLayout auth={auth}>{children}</PresentationLayout>
            </ThemeProvider>
          </AppRouterCacheProvider>
        </MeProvider>
      </body>
    </html>
  );
}
